name: Deploy Bicep

on:
  push:
    branches: [ dev, main ]
    paths:
      - 'main.bicep'
      - 'parameters/**'
      - 'config/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: What-if (Dev)
        run: |
          az deployment group what-if \
            --resource-group "${{ vars.RESOURCE_GROUP }}" \
            --template-file main.bicep \
            --parameters @"${{ vars.PARAMETERS_FILE }}" \
            --name "whatif-${{ github.run_id }}"

      - name: Deploy (Dev)
        run: |
          az deployment group create \
            --resource-group "${{ vars.RESOURCE_GROUP }}" \
            --template-file main.bicep \
            --parameters @"${{ vars.PARAMETERS_FILE }}" \
            --name "deploy-${{ github.run_id }}"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    name: Deploy to Prod
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: What-if (Prod)
        run: |
          az deployment group what-if \
            --resource-group "${{ vars.RESOURCE_GROUP }}" \
            --template-file main.bicep \
            --parameters @"${{ vars.PARAMETERS_FILE }}" \
            --name "whatif-${{ github.run_id }}"

      - name: Deploy (Prod)
        run: |
          az deployment group create \
            --resource-group "${{ vars.RESOURCE_GROUP }}" \
            --template-file main.bicep \
            --parameters @"${{ vars.PARAMETERS_FILE }}" \
            --name "deploy-${{ github.run_id }}"
